stages:
  - build
  - test
  - document

image: gcc
before_script:
 - apt-get update --yes
 - apt-get install --yes cmake doxygen

build:
  stage: build
  script:
    - mkdir build && cd build; cmake ..; make
  artifacts:
    paths:
      - bin/*

test:
  stage: test
  script:
    - mkdir build && cd build; cmake ..; ctest

document:
    stage: document
    script:
    - mkdir build && cd build; cmake ..; make doxygen
    artifacts:
    paths:
      - doc/*    
