stages:
  - build
  - test

build:
  stage: build
  script:
    - mkdir build && cd build; cmake ..; make -j
  artifacts:
    paths:
      - build/*

test:
  stage: test
  script:
    - cd build && ctest